version: '3.4'

x-shared-env: &shared-env
  NODE_ENV: 'development'
  IS_DOCKER: 'true'
  CHOKIDAR_USEPOLLING: 'true'

services:

  client:
    build:
      context: ../client
    volumes:
      - ../client:/var/lib/client:delegated
      - /var/lib/client/node_modules/
    ports:
    - '3000:3000'
    environment:
      <<: *shared-env
    container_name: client
    tty: true
    networks:
      - frontend

  server:
    build:
      context: ../server
    volumes:
      - ../server:/var/lib/server:delegated
      - /var/lib/server/node_modules/
    ports:
      - '4000:4000'
    environment:
      <<: *shared-env
    container_name: server
    networks:
      - backend

networks:
    frontend:
    backend:
